name: Deploy to S3 and Lambda

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install zip utility
        run: sudo apt-get install zip

      - name: Zip Lambda function
        run: |
          cd lambda
          zip -r ../function.zip .
          cd ..

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-1  

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{secrets.LAMBDA_FUNCTION}} \
            --zip-file fileb://function.zip \
            --region eu-north-1

      - name: Deploy to S3
        run: |
          aws s3 sync ./ s3://${{secrets.BUCKET_NAME}} --exclude ".git/*" --exclude ".github/*" --delete
