name: Deploy Infra and App

on:
  push:
    branches:
      - main

jobs:
  terraform:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: terra

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.5.6

      - name: Configure AWS credentials for Terraform
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_REGION }}

      - name: Terraform Init
        run: terraform init

      - name: Terraform Plan
        run: terraform plan -var="bucket_name=${{ secrets.BUCKET_NAME }}" -var="aws_region=${{ secrets.S3_REGION }}"

      - name: Terraform Apply
        run: terraform apply -var="bucket_name=${{ secrets.BUCKET_NAME }}" -var="aws_region=${{ secrets.S3_REGION }}" -auto-approve

  deploy:
    needs: terraform
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install zip utility
        run: sudo apt-get install zip

      - name: Zip Lambda function
        run: |
          cd lambda
          zip -r ../function.zip .
          cd ..

      - name: Configure AWS credentials (Lambda region)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.LAMBDA_REGION }}

      - name: Deploy Lambda function
        run: |
          aws lambda update-function-code \
            --function-name ${{ secrets.LAMBDA_FUNCTION }} \
            --zip-file fileb://function.zip \
            --region ${{ secrets.LAMBDA_REGION }}

      - name: Configure AWS credentials (S3 region)
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.S3_REGION }}

      - name: Sync static site to S3
        run: |
          aws s3 sync ./ s3://${{ secrets.BUCKET_NAME }} --delete --exclude ".git/*" --exclude "lambda/*" --exclude "terra/*" --exclude ".github/*"

